name: Build Resource Pack

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Zip resource pack
      run: |
        zip -r elgeis-resourcepack.zip assets pack.mcmeta

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ResourcePack
        path: resourcepack.zip

    - name: Create or update 'latest' release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: elgeis-resourcepack.zip
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
